id: P000453
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W19829
  title: འབོ་གངས་དཀར་རྣམ་ཐར།
  author: ''
  volumes:
    377517d8a205488c99e40cd257f760c3:
      image_group_id: I1GS105450
      title: Volume 1 of 'bo gangs dkar rnam thar
      volume_number: 1
      total_pages: 104
      base_file: v001.txt
